### ISSUE TITLE
IOs Version 

### ISSUE THREAD

**Issue by kodatech** [darde/react-native-sidemenu#2]
Hey, thanks for the example. It's very good. Are you thinking in upload the IOs version? Thanks

**Comment by darde** [comment]
Hey @kodatech , thanks. I need a mac in order to release an iOS version. I can't promise, but I will try with a friend. Any way, I think we need few changes to run on iOS.

**Comment by darde** [comment]
Was not possibly generate an iOS version yet. If you need an iOS version you can check [this repo](https://github.com/react-native-community/react-native-side-menu).
