### ISSUE TITLE
menuItems and LighthouseBody get database ?

### ISSUE THREAD

**Issue by hulusiM** [darde/react-native-sidemenu#5]
export const menuItems = [
  {
    thumb: 'lighthouse_lindau',
    index: 1,
    label: 'Lindau Lighthouse, Germany',
  },
  ....
];
**Can I get it from the database menuItems,LighthouseBody  ??**

**Comment by darde** [comment]
Hi @hulusimizrak , thanks for your issue. Yes, you can pull this information from a database. You can create a file to manage the database connection and export your async calls.

**Comment by hulusiM** [comment]
Thank you to @darde , I fill lighthouses, right ?

```
 componentWillMount(){
    fetch('http://...........................')
    .then((response) => response.json())
    .then((responseJson) => {
     
      this.setState(
        update(this.state, {                       
            $set: {
              lighthouses: responseJson
            }    
        })
      );
    })
    .catch((error) => {
        console.error(error);
    });
  }
```


It works like this :)

**Comment by darde** [comment]
Almost there. According to the Facebook docs, the most suitable place to fetch your data is in **componentDidMount**. See the [official docs](https://facebook.github.io/react/docs/react-component.html#componentdidmount) for this. Just change the method ;)
